import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

type Props = {
  id: string;
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  params,
  res,
}) => {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  return {
    props: {
      id: `1000${params ? params?.id : 0}`,
    },
  };
};

const Home: NextPage<Props> = ({ id }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex flex-col px-4 py-2">
        <p className="text-xl">post id: {id}</p>
      </main>

      <footer className="px-4">
        <p className="text-sm">&copy; 2022</p>
      </footer>
    </div>
  );
};

export default Home;
