import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

type Props = {
  time: string;
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  res,
}) => {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=60"
  );

  return {
    props: {
      time: new Date().toISOString(),
    },
  };
};

const Home: NextPage<Props> = ({ time }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex flex-col px-4 py-2">
        <h1 className="text-2xl font-bold">cached time</h1>
        <p className="text-xl">{time}</p>
      </main>

      <footer className="px-4">
        <p className="text-sm">&copy; 2022</p>
      </footer>
    </div>
  );
};

export default Home;
