import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

type Props = {
  time: string;
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  res,
}) => {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  return {
    props: {
      time: new Date().toISOString(),
    },
  };
};

const Home: NextPage<Props> = ({ time }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home</h1>
        <p>{time}</p>
      </main>

      <footer>
        <p>&copy; 2022</p>
      </footer>
    </div>
  );
};

export default Home;
