import { NextPage } from "next";
import Head from "next/head";

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SSG | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>SSG Page</h1>
      </main>
    </div>
  );
};

export default Page;
